apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: gitea-team
  annotations:
    meta.crossplane.io/maintainer: W'xOps Platform Team
    meta.crossplane.io/description: Manages a Gitea team and its membership within an organization via Crossplane.
    meta.crossplane.io/source: github.com/wxops/wxops-core
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v2.3.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-terraform
      version: ">=v1.1.4"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.10.6"
