#!/usr/bin/env python3
"""
Generate an observed.yaml fixture for a test case.

Readiness in these compositions is derived from `option("params").ocds` — the
observed state of composed resources — so a case with no observed.yaml only ever
exercises the first-reconcile path where everything is false. To test the ready
path you need a fixture, and it has two easy-to-get-wrong details:

  1. ocds is keyed by the Object's metadata.name, and Crossplane rewrites
     crossplane.io/composition-resource-name to that same value. A fixture whose
     annotation says anything else is silently dropped.
  2. Observed replica counts live at Object.status.atProvider.manifest.status,
     not at Object.status — provider-kubernetes writes the wrapped resource back
     there.

This renders the case, reads the real Object names out, and emits a fixture with
every resource Ready.

Usage:
    python3 tests/lib/mkobserved.py <package> <case> [--unready NAME ...]

    --unready takes an Object-name suffix, e.g. --unready certificate
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render as R  # noqa: E402
import yaml  # noqa: E402


def build(package: str, case: str, unready: list[str]) -> str:
    case_dir = R.CASES / package / case
    ok, out, err = R.render(case_dir, package)
    if not ok:
        print(f"render failed: {err}", file=sys.stderr)
        sys.exit(1)

    docs = R.load_docs(out)
    xr = next((d for d in docs
               if "crossplane.io/composition-resource-name"
               not in ((d.get("metadata") or {}).get("annotations") or {})), {})
    composite = (xr.get("metadata") or {}).get("name", "")

    entries = []
    for d in docs:
        meta = d.get("metadata") or {}
        ann = meta.get("annotations") or {}
        if "crossplane.io/composition-resource-name" not in ann:
            continue
        name = meta.get("name")
        is_ready = not any(u in name for u in unready)
        entry = {
            "apiVersion": d.get("apiVersion"),
            "kind": d.get("kind"),
            "metadata": {
                "name": name,
                # Must equal metadata.name — see docstring.
                "annotations": {"crossplane.io/composition-resource-name": name},
                "labels": {"crossplane.io/composite": composite},
            },
            "status": {
                "conditions": [{
                    "type": "Ready",
                    "status": "True" if is_ready else "False",
                    "reason": "Available" if is_ready else "Creating",
                }],
            },
        }
        wrapped = ((d.get("spec") or {}).get("forProvider") or {}).get("manifest") or {}
        if wrapped.get("kind") == "Deployment":
            replicas = ((wrapped.get("spec") or {}).get("replicas")) or 1
            entry["status"]["atProvider"] = {
                "manifest": {"status": {"readyReplicas": replicas if is_ready else 0}}
            }
        entries.append(entry)

    header = (
        "# GENERATED by tests/lib/mkobserved.py — safe to hand-edit.\n"
        "#\n"
        "# Mocked observed state of this case's composed resources, fed to render\n"
        "# via --observed-resources so readiness derivation can be exercised.\n"
        "# crossplane.io/composition-resource-name MUST equal metadata.name or the\n"
        "# entry is silently ignored.\n"
    )
    if unready:
        header += f"# Deliberately not Ready: {', '.join(unready)}\n"
    return header + R.dump_all(entries)


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) < 2:
        print(__doc__)
        return 2
    unready: list[str] = []
    if "--unready" in sys.argv:
        unready = sys.argv[sys.argv.index("--unready") + 1:]
        unready = [u for u in unready if not u.startswith("--")]

    package, case = args[0], args[1]
    text = build(package, case, unready)
    dest = R.CASES / package / case / "observed.yaml"
    dest.write_text(text)
    print(f"wrote {dest.relative_to(R.ROOT)}"
          + (f"  (unready: {', '.join(unready)})" if unready else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
