apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-wxops-gitea-org
  annotations:
    meta.crossplane.io/version: v0.1.0
spec:
  package: ghcr.io/wxops/platform-wxops-gitea-org:v0.1.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic

  # packagePullSecretRef:
  #   name: registry-credentials
  #   namespace: crossplane-system
