apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-wxops-gitea-user
  annotations:
    meta.crossplane.io/version: v0.1.0
spec:
  package: gitea.xeusnguyen.xyz/platform-team/platform-wxops-gitea-user:v0.1.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic

  # packagePullSecretRef:
  #   name: registry-credentials
  #   namespace: crossplane-system
