apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: wxops-core-gitea-team
spec:
  package: ghcr.io/wxops/wxops-core/gitea-team:release-2026-09-16
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic

  # packagePullSecretRef:
  #   name: registry-credentials
  #   namespace: crossplane-system
