apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: wxops-core-tenant-database
  annotations:
    meta.crossplane.io/version: v0.1.0
spec:
  package: gitea.xeusnguyen.xyz/platform-team/wxops-core-tenant-database:v0.1.5
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
