apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-wxops-tenant-database
  annotations:
    meta.crossplane.io/version: v0.1.0
spec:
  package: gitea.xeusnguyen.xyz/platform-team/platform-wxops-tenant-database:v0.1.2
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
