apiVersion: platform.wxops.cloud/v1alpha1
kind: XTenantDatabase
metadata:
  name: rocket-team-analytics-db
spec:
  parameters:
    tier: dedicated
    environment: dev
    dedicatedCluster:
      instances: 3           # HA cluster
      storageSize: "50Gi"
      postgresVersion: 16
      enablePooler: true
      # namespace: cnpg-system  # default

    dbName: analytics-db
    owner: rocket-team
    extensions:
      - uuid-ossp
      - pgcrypto

    # databaseReclaimPolicy: "retain"
    vaultSecretStoreName: "vault-cluster-store"
