apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: wxops-core-tenant-app
  annotations:
    meta.crossplane.io/maintainer: W'xOps Platform Team
    meta.crossplane.io/description: Tenant application scaffold (Deployment, Service, Ingress, optional Darlane) with secretsFrom wiring, cert-manager TLS, and oauth2-proxy SSO.
    meta.crossplane.io/source: github.com/wxops/wxops-core
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v2.3.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v1.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.12.1"
